### ISSUE TITLE
Identification of which pin triggered the External Interrupt from the port.

### ISSUE THREAD

**Issue by RahulGoyal-tech** [gicking/STM8_headers#12]
if on port b i have 2 pins 0, 4 set as external interrupt, and external interrupt is triggered, how do i know which pin triggered the interrupt in STM8S003F3 baremetal programming

I am expecting some sort of register / flag that i can check if is set or not to verify which pin called the external interrupt.

**Comment by gicking** [comment]
Hello Rahul,unfortunately the STM8S has no register to indicate the respective pin for a port interrupt directly. Therefore you have to do this via software. Attached please find an example which demonstrates how you can do this. Unfortunately I am on a business trip, so I couldn’t test it. Can you please let me now if this works for you? If yes, I will change the port interrupt example accordingly.Regards, GeorgAm 18.11.2024 22:03 schrieb Rahul Goyal ***@***.***>:
if on port b i have 2 pins 0, 4 set as external interrupt, and external interrupt is triggered, how do i know which pin triggered the interrupt in STM8S003F3 baremetal programming
I am expecting some sort of register / flag that i can check if is set or not to verify which pin called the external interrupt.

**Comment by RahulGoyal-tech** [comment]
Hi @gicking,
Can't find any attachment here 😅

**Comment by gicking** [comment]
I currently have no access to my GitHub password. If you send me your mail address, I can send the code via PMAm 19.11.2024 10:19 schrieb Rahul Goyal ***@***.***>:
Hi @gicking,
Can't find any attachment here 😅

**Comment by RahulGoyal-tech** [comment]
Sure my mail Id : rhgoyal01@gmail.com

**Comment by gicking** [comment]
please see a working example under "[examples/port_interrupt_multiple](https://github.com/gicking/STM8_headers/tree/master/examples/port_interrupt_multiple)"

Note that rising and falling edges must be handled in the ISR -> port interrupt sensitivity must be changing

**Comment by RahulGoyal-tech** [comment]
I had some doubt. In the code section:
![image](https://github.com/user-attachments/assets/2dc6d803-131a-4a7a-948c-97f820065959)
if we take default state. then if we receive rising, we will never be able to detect that because old state will always be 0xFF and if the new state is also high, then as per logic, we will get false and rising will not be detected.
Did you test this out?? Did it work for you?

**Comment by RahulGoyal-tech** [comment]
Code line 183 - 204

**Comment by gicking** [comment]
You are partly correct. When you set the value of a **static** local variable in a routine, it is initialized only once (see e.g. [here](https://www.geeksforgeeks.org/g-fact-80/)). Therefore you may only miss the first rising edge for each pin, depending on the initial pin states, and how you initialize `state_old`. 

To avoid this, I have now made `state_old` a global variable and read in the port state at the end of the initialization in `main()`. That way I don't assume the initial state but simply read it. Hope this solves your problem...!?
