### ISSUE TITLE
STM8L151G6 Extra lines

### ISSUE THREAD

**Issue by Sawaiz** [gicking/STM8_headers#3]
I think these two lines are duplicates of later lines where the union does close properly. SDCC was giving errors on including the header file. I removed them nd was able to compile.

https://github.com/gicking/STM8_headers/blob/13f3ecd21f59943fdc0cbcf312cb61afc0c9d450/include/STM8L151G6.h#L2554

https://github.com/gicking/STM8_headers/blob/13f3ecd21f59943fdc0cbcf312cb61afc0c9d450/include/STM8L151G6.h#L2512

**Comment by gicking** [comment]
thanks for pointing this out! I found that there are more headers with this issue. It happens when the header generator script finds shared registers at the same address. I fixed it now. Can you please try again? Thanks!

**Comment by Sawaiz** [comment]
Yeah, seems to work fine. Thanks for making this, saves me a from hours of building a register map!

**Comment by gicking** [comment]
:-)  that was the idea
