### ISSUE TITLE
Why BITS?

### ISSUE THREAD

**Issue by spth** [gicking/STM8_headers#7]
What is the motivation for the BITS macro?
Wouldn't it work just as well, to just use unsigned int as type for for the bitfields, and not define the BITS macro at all? Especially since a name like BITS has a high risk of clashing with an identifier from the user?

**Comment by gicking** [comment]
"unsigned int" doesn't work for IAR, which requires "unsigned char" 

But you are correct, maybe the choice of BITS was not the best one...  However, the scope of BITS is limited to the device header, as it is undefined at the very bottom. Does this avoid a possible conflict with a user macro?

**Comment by spth** [comment]
What is the problem with unsigned int on IAR? The C standard mandates support for unsigned int bitfields (but not for unsigned char).

**Comment by gicking** [comment]
Don't ask me! It simply failed with "unsigned int" and works with "unsigned char". That was purely empirical...

But I will try it again, if you think it should work. Maybe I did something wrong in the configuration. Do you have IAR installed for a trial?

**Comment by gicking** [comment]
It seems like IAR is indeed deviating from the C standard. See e.g. page 216 in this [ARM development guide](http://www.iarsys.co.jp/download/LMS2/arm/7502/ewarm7502doc/arm/doc/EWARM_DevelopmentGuide.ENU.pdf), or this [technical note](https://www.iar.com/knowledge/support/technical-notes/compiler/bit-access/)

Also, I tried again using the attached [test.zip](https://github.com/gicking/STM8_headers/files/6289558/test.zip), and "unsigned char" works (=LED blinks), but "unsigned int" not (=LED off).

**Comment by roybaer** [comment]
I would recommend to rename BITS to something a little bit less collision-prone, like e.g. BITFIELD_UINT.
Undefining a macro at the end of the header only helps if the user tries to define the same macro _after_ the header inclusion.

**Comment by gicking** [comment]
ok, will do...

**Comment by gicking** [comment]
done
